import { SemesterEnum } from "@/common/enum/semesterEnum"
import { WeekdayEnum } from "@/common/enum/weekdayEnum"
import type Lecture from "@/common/interface/Lecture"

const UserLectures: Lecture[] = [
  {
    id: 3678,
    old_code: "CBE342",
    department: 0,
    title: "화학 및 생물 제품디자인",
    title_en: "Chemical and Biological Product Design",
    type: "전공선택",
    type_en: "Major Elective",
    review_total_weight: 0,
    professors: [
      {
        professor_id: 695,
        name: "장용근",
        name_en: "",
        review_total_weight: 0,
      },
    ],
    grade: 0,
    load: 0,
    speech: 0,
    credit: 4,
    credit_au: 0,
    num_classes: 2,
    num_labs: 2,
    limit: 50,
    classtimes: [
      {
        day: 1,
        timeIndex: 0,
        duration: 3,
        startTime: "",
        endTime: "",
      },
      {
        day: 3,
        timeIndex: 4,
        duration: 3,
        startTime: "",
        endTime: "",
      },
    ],
    examtimes: [
      {
        day: WeekdayEnum.Mon,
        timeIndex: 4, // 10:00 ~ 12:00
        startTime: "10:00",
        endTime: "12:00",
        duration: 4,
      },
    ],
    classroom: "(E2) 산업경영학동 1225",
    classroom_en: "B102",
    course: 3678,
    class_no: "",
    year: 0,
    semester: SemesterEnum.SPRING,
    code: "CBE342",
    department_code: "",
    department_name: "",
    department_name_en: "",
    num_people: 0,
    is_english: false,
    common_title: "",
    common_title_en: "",
    class_title: "",
    class_title_en: "",
  },
  {
    id: 295,
    old_code: "CBE441",
    department: 0,
    title: "공정 및 제품 디자인",
    title_en: "Techniques of Process and Product Design",
    type: "전공선택",
    type_en: "Major Elective",
    review_total_weight: 0,
    professors: [
      {
        professor_id: 1853,
        name: "이재우",
        name_en: "",
        review_total_weight: 0,
      },
      {
        professor_id: 695,
        name: "장용근",
        name_en: "",
        review_total_weight: 0,
      },
    ],
    grade: 0,
    speech: 0,
    load: 0,
    credit: 4,
    credit_au: 0,
    num_classes: 3,
    num_labs: 1,
    limit: 20,
    classtimes: [
      {
        day: 1,
        timeIndex: 5,
        duration: 6,
        startTime: "",
        endTime: "",
      },
      {
        day: 2,
        timeIndex: 8,
        duration: 3,
        startTime: "",
        endTime: "",
      },
    ],
    examtimes: [
      {
        day: WeekdayEnum.Wed,
        timeIndex: 10, // 14:00 ~ 16:00
        startTime: "14:00",
        endTime: "16:00",
        duration: 4,
      },
    ],
    classroom: "(W1-3) 응용공학동 (2501-1호) 세미나실",
    classroom_en: "(W1-3) Applied Enginnering B/D (2501-1) Seminar Room",
    course: 295,
    class_no: "",
    year: 0,
    semester: SemesterEnum.SPRING,
    code: "CBE441",
    department_code: "",
    department_name: "",
    department_name_en: "",
    num_people: 0,
    is_english: false,
    common_title: "",
    common_title_en: "",
    class_title: "",
    class_title_en: "",
  },
  {
    id: 1599,
    old_code: "CBE442",
    department: 0,
    title: "생명화학공학 디자인 프로젝트",
    title_en: "Chemical and Biomolecular Engineering Capstone Design Project",
    type: "전공필수",
    type_en: "Major Required",
    professors: [
      {
        professor_id: 2023,
        name: "리섕",
        name_en: "",
        review_total_weight: 0,
      },
    ],
    grade: 15,
    load: 6,
    speech: 12,
    credit: 3,
    credit_au: 0,
    num_classes: 3,
    num_labs: 0,
    limit: 70,
    classtimes: [],
    examtimes: [
      {
        day: WeekdayEnum.Thu,
        timeIndex: 12,
        startTime: "16:00",
        endTime: "18:00",
        duration: 4,
      },
    ],
    classroom: "(W1-1) 응용공학동 2122",
    classroom_en: "(W1-1) Applied Enginnering B/D 2122",
    course: 0,
    class_no: "",
    year: 0,
    semester: SemesterEnum.SPRING,
    code: "CBE442",
    department_code: "",
    department_name: "",
    department_name_en: "",
    num_people: 0,
    is_english: false,
    common_title: "",
    common_title_en: "",
    class_title: "",
    class_title_en: "",
    review_total_weight: 0,
  },
  {
    id: 3679,
    old_code: "CBE342",
    department: 0,
    title: "화학 및 생물 제품디자인",
    title_en: "Chemical and Biological Product Design",
    type: "전공선택",
    type_en: "Major Elective",
    review_total_weight: 0,
    professors: [
      {
        professor_id: 695,
        name: "장용근",
        name_en: "",
        review_total_weight: 0,
      },
    ],
    grade: 0,
    load: 0,
    speech: 0,
    credit: 4,
    credit_au: 0,
    num_classes: 2,
    num_labs: 2,
    limit: 50,
    classtimes: [
      {
        day: 1,
        timeIndex: 0,
        duration: 3,
        startTime: "",
        endTime: "",
      },
      {
        day: 3,
        timeIndex: 4,
        duration: 3,
        startTime: "",
        endTime: "",
      },
    ],
    examtimes: [
      {
        day: WeekdayEnum.Mon,
        timeIndex: 4, // 10:00 ~ 12:00
        startTime: "10:00",
        endTime: "12:00",
        duration: 4,
      },
    ],
    classroom: "(E2) 산업경영학동 1225",
    classroom_en: "B102",
    course: 3679,
    class_no: "",
    year: 1,
    semester: SemesterEnum.SPRING,
    code: "CBE342",
    department_code: "",
    department_name: "",
    department_name_en: "",
    num_people: 0,
    is_english: false,
    common_title: "",
    common_title_en: "",
    class_title: "",
    class_title_en: "",
  },
  {
    id: 296,
    old_code: "CBE441",
    department: 0,
    title: "공정 및 제품 디자인",
    title_en: "Techniques of Process and Product Design",
    type: "전공선택",
    type_en: "Major Elective",
    review_total_weight: 0,
    professors: [
      {
        professor_id: 1853,
        name: "이재우",
        name_en: "",
        review_total_weight: 0,
      },
      {
        professor_id: 695,
        name: "장용근",
        name_en: "",
        review_total_weight: 0,
      },
    ],
    grade: 0,
    speech: 0,
    load: 0,
    credit: 4,
    credit_au: 0,
    num_classes: 3,
    num_labs: 1,
    limit: 20,
    classtimes: [
      {
        day: 1,
        timeIndex: 5,
        duration: 6,
        startTime: "",
        endTime: "",
      },
      {
        day: 2,
        timeIndex: 8,
        duration: 3,
        startTime: "",
        endTime: "",
      },
    ],
    examtimes: [
      {
        day: WeekdayEnum.Wed,
        timeIndex: 10, // 14:00 ~ 16:00
        startTime: "14:00",
        endTime: "16:00",
        duration: 4,
      },
    ],
    classroom: "(W1-3) 응용공학동 (2501-1호) 세미나실",
    classroom_en: "(W1-3) Applied Enginnering B/D (2501-1) Seminar Room",
    course: 296,
    class_no: "",
    year: 1,
    semester: SemesterEnum.SPRING,
    code: "CBE441",
    department_code: "",
    department_name: "",
    department_name_en: "",
    num_people: 0,
    is_english: false,
    common_title: "",
    common_title_en: "",
    class_title: "",
    class_title_en: "",
  },
  {
    id: 1600,
    old_code: "CBE442",
    department: 0,
    title: "생명화학공학 디자인 프로젝트",
    title_en: "Chemical and Biomolecular Engineering Capstone Design Project",
    type: "전공필수",
    type_en: "Major Required",
    professors: [
      {
        professor_id: 2023,
        name: "리섕",
        name_en: "",
        review_total_weight: 0,
      },
    ],
    grade: 15,
    load: 6,
    speech: 12,
    credit: 3,
    credit_au: 0,
    num_classes: 3,
    num_labs: 0,
    limit: 70,
    classtimes: [],
    examtimes: [
      {
        day: WeekdayEnum.Thu,
        timeIndex: 12,
        startTime: "16:00",
        endTime: "18:00",
        duration: 4,
      },
    ],
    classroom: "(W1-1) 응용공학동 2122",
    classroom_en: "(W1-1) Applied Enginnering B/D 2122",
    course: 0,
    class_no: "",
    year: 1,
    semester: SemesterEnum.SPRING,
    code: "CBE442",
    department_code: "",
    department_name: "",
    department_name_en: "",
    num_people: 0,
    is_english: false,
    common_title: "",
    common_title_en: "",
    class_title: "",
    class_title_en: "",
    review_total_weight: 0,
  },

  {
    id: 3680,
    old_code: "CBE342",
    department: 0,
    title: "화학 및 생물 제품디자인",
    title_en: "Chemical and Biological Product Design",
    type: "전공선택",
    type_en: "Major Elective",
    review_total_weight: 0,
    professors: [
      {
        professor_id: 695,
        name: "장용근",
        name_en: "",
        review_total_weight: 0,
      },
    ],
    grade: 0,
    load: 0,
    speech: 0,
    credit: 4,
    credit_au: 0,
    num_classes: 2,
    num_labs: 2,
    limit: 50,
    classtimes: [
      {
        day: 1,
        timeIndex: 0,
        duration: 3,
        startTime: "",
        endTime: "",
      },
      {
        day: 3,
        timeIndex: 4,
        duration: 3,
        startTime: "",
        endTime: "",
      },
    ],
    examtimes: [
      {
        day: WeekdayEnum.Mon,
        timeIndex: 4, // 10:00 ~ 12:00
        startTime: "10:00",
        endTime: "12:00",
        duration: 4,
      },
    ],
    classroom: "(E2) 산업경영학동 1225",
    classroom_en: "B102",
    course: 3680,
    class_no: "",
    year: 2,
    semester: SemesterEnum.SPRING,
    code: "CBE342",
    department_code: "",
    department_name: "",
    department_name_en: "",
    num_people: 0,
    is_english: false,
    common_title: "",
    common_title_en: "",
    class_title: "",
    class_title_en: "",
  },
  {
    id: 297,
    old_code: "CBE441",
    department: 0,
    title: "공정 및 제품 디자인",
    title_en: "Techniques of Process and Product Design",
    type: "전공선택",
    type_en: "Major Elective",
    review_total_weight: 0,
    professors: [
      {
        professor_id: 1853,
        name: "이재우",
        name_en: "",
        review_total_weight: 0,
      },
      {
        professor_id: 695,
        name: "장용근",
        name_en: "",
        review_total_weight: 0,
      },
    ],
    grade: 0,
    speech: 0,
    load: 0,
    credit: 4,
    credit_au: 0,
    num_classes: 3,
    num_labs: 1,
    limit: 20,
    classtimes: [
      {
        day: 1,
        timeIndex: 5,
        duration: 6,
        startTime: "",
        endTime: "",
      },
      {
        day: 2,
        timeIndex: 8,
        duration: 3,
        startTime: "",
        endTime: "",
      },
    ],
    examtimes: [
      {
        day: WeekdayEnum.Wed,
        timeIndex: 10, // 14:00 ~ 16:00
        startTime: "14:00",
        endTime: "16:00",
        duration: 4,
      },
    ],
    classroom: "(W1-3) 응용공학동 (2501-1호) 세미나실",
    classroom_en: "(W1-3) Applied Enginnering B/D (2501-1) Seminar Room",
    course: 297,
    class_no: "",
    year: 2,
    semester: SemesterEnum.SPRING,
    code: "CBE441",
    department_code: "",
    department_name: "",
    department_name_en: "",
    num_people: 0,
    is_english: false,
    common_title: "",
    common_title_en: "",
    class_title: "",
    class_title_en: "",
  },
  {
    id: 1601,
    old_code: "CBE442",
    department: 0,
    title: "생명화학공학 디자인 프로젝트",
    title_en: "Chemical and Biomolecular Engineering Capstone Design Project",
    type: "전공필수",
    type_en: "Major Required",
    professors: [
      {
        professor_id: 2023,
        name: "리섕",
        name_en: "",
        review_total_weight: 0,
      },
    ],
    grade: 15,
    load: 6,
    speech: 12,
    credit: 3,
    credit_au: 0,
    num_classes: 3,
    num_labs: 0,
    limit: 70,
    classtimes: [],
    examtimes: [
      {
        day: WeekdayEnum.Thu,
        timeIndex: 12,
        startTime: "16:00",
        endTime: "18:00",
        duration: 4,
      },
    ],
    classroom: "(W1-1) 응용공학동 2122",
    classroom_en: "(W1-1) Applied Enginnering B/D 2122",
    course: 1601,
    class_no: "",
    year: 2,
    semester: SemesterEnum.SPRING,
    code: "CBE442",
    department_code: "",
    department_name: "",
    department_name_en: "",
    num_people: 0,
    is_english: false,
    common_title: "",
    common_title_en: "",
    class_title: "",
    class_title_en: "",
    review_total_weight: 0,
  },

  {
    id: 3681,
    old_code: "CBE342",
    department: 0,
    title: "화학 및 생물 제품디자인",
    title_en: "Chemical and Biological Product Design",
    type: "전공선택",
    type_en: "Major Elective",
    review_total_weight: 0,
    professors: [
      {
        professor_id: 695,
        name: "장용근",
        name_en: "",
        review_total_weight: 0,
      },
    ],
    grade: 0,
    load: 0,
    speech: 0,
    credit: 4,
    credit_au: 0,
    num_classes: 2,
    num_labs: 2,
    limit: 50,
    classtimes: [
      {
        day: 1,
        timeIndex: 0,
        duration: 3,
        startTime: "",
        endTime: "",
      },
      {
        day: 3,
        timeIndex: 4,
        duration: 3,
        startTime: "",
        endTime: "",
      },
    ],
    examtimes: [
      {
        day: WeekdayEnum.Mon,
        timeIndex: 4, // 10:00 ~ 12:00
        startTime: "10:00",
        endTime: "12:00",
        duration: 4,
      },
    ],
    classroom: "(E2) 산업경영학동 1225",
    classroom_en: "B102",
    course: 3681,
    class_no: "",
    year: 3,
    semester: SemesterEnum.SPRING,
    code: "CBE342",
    department_code: "",
    department_name: "",
    department_name_en: "",
    num_people: 0,
    is_english: false,
    common_title: "",
    common_title_en: "",
    class_title: "",
    class_title_en: "",
  },
  {
    id: 298,
    old_code: "CBE441",
    department: 0,
    title: "공정 및 제품 디자인",
    title_en: "Techniques of Process and Product Design",
    type: "전공선택",
    type_en: "Major Elective",
    review_total_weight: 0,
    professors: [
      {
        professor_id: 1853,
        name: "이재우",
        name_en: "",
        review_total_weight: 0,
      },
      {
        professor_id: 695,
        name: "장용근",
        name_en: "",
        review_total_weight: 0,
      },
    ],
    grade: 0,
    speech: 0,
    load: 0,
    credit: 4,
    credit_au: 0,
    num_classes: 3,
    num_labs: 1,
    limit: 20,
    classtimes: [
      {
        day: 1,
        timeIndex: 5,
        duration: 6,
        startTime: "",
        endTime: "",
      },
      {
        day: 2,
        timeIndex: 8,
        duration: 3,
        startTime: "",
        endTime: "",
      },
    ],
    examtimes: [
      {
        day: WeekdayEnum.Wed,
        timeIndex: 10, // 14:00 ~ 16:00
        startTime: "14:00",
        endTime: "16:00",
        duration: 4,
      },
    ],
    classroom: "(W1-3) 응용공학동 (2501-1호) 세미나실",
    classroom_en: "(W1-3) Applied Enginnering B/D (2501-1) Seminar Room",
    course: 298,
    class_no: "",
    year: 3,
    semester: SemesterEnum.SPRING,
    code: "CBE441",
    department_code: "",
    department_name: "",
    department_name_en: "",
    num_people: 0,
    is_english: false,
    common_title: "",
    common_title_en: "",
    class_title: "",
    class_title_en: "",
  },
  {
    id: 1602,
    old_code: "CBE442",
    department: 0,
    title: "생명화학공학 디자인 프로젝트",
    title_en: "Chemical and Biomolecular Engineering Capstone Design Project",
    type: "전공필수",
    type_en: "Major Required",
    professors: [
      {
        professor_id: 2023,
        name: "리섕",
        name_en: "",
        review_total_weight: 0,
      },
    ],
    grade: 15,
    load: 6,
    speech: 12,
    credit: 3,
    credit_au: 0,
    num_classes: 3,
    num_labs: 0,
    limit: 70,
    classtimes: [],
    examtimes: [
      {
        day: WeekdayEnum.Thu,
        timeIndex: 12,
        startTime: "16:00",
        endTime: "18:00",
        duration: 4,
      },
    ],
    classroom: "(W1-1) 응용공학동 2122",
    classroom_en: "(W1-1) Applied Enginnering B/D 2122",
    course: 1602,
    class_no: "",
    year: 3,
    semester: SemesterEnum.SPRING,
    code: "CBE442",
    department_code: "",
    department_name: "",
    department_name_en: "",
    num_people: 0,
    is_english: false,
    common_title: "",
    common_title_en: "",
    class_title: "",
    class_title_en: "",
    review_total_weight: 0,
  },
]

export default UserLectures
